### ISSUE TITLE
"Requested Inventory is protected" LAN SERVER

### ISSUE THREAD

**Issue by Zano1999** [PotatoPresident/InvView#11]
When i try to open a player inventory in a lan server it say: "Requested Inventory is protected"

I already saw i need op, but there's no op command during a LAN session

**Comment by PotatoPresident** [comment]
All operator inventories are protected by default. Evidently, the players inventory you tried to open also has OP. Try opening to LAN with cheats off.

**Comment by Zano1999** [comment]
If i write the command with cheats off the game crash, there's no way to disable the permission system?

**Comment by yitzy299** [comment]
> If i write the command with cheats off the game crash, there's no way to disable the permission system?

Please send logs and install byMatrixx/wdmcf

**Comment by yitzy299** [comment]
![image](https://user-images.githubusercontent.com/66269211/107857417-3d3aac00-6e26-11eb-9235-3508cfca7b40.png)
You can't run the command without cheats so it doesn't crash

**Comment by Zano1999** [comment]
> > If i write the command with cheats off the game crash, there's no way to disable the permission system?
> 
> Please install https://github.com/ByMartrixx/wdmcf and send the logs

With cheats enabled: https://pastebin.com/BTKcN93E

**Comment by Merith-TK** [comment]
> All operator inventories are protected by default. Evidently, the players inventory you tried to open also has OP. Try opening to LAN with cheats off.

is there a way to disable this functionality? or grant a single OP permission to view op inventories?
