### ISSUE TITLE
Short cuts cause crash

### ISSUE THREAD

**Issue by ethans0061** [PotatoPresident/InvView#12]
**Describe the bug**
Crashes server when using regular chest / inv shortcuts

**To Reproduce**
1. Use regular chest shortcuts such as:
2. Shift click or Shift double click while holding item to move all of one type.

**Expected behavior**
The server will freeze - a single tick took greater than 60 seconds - shutting down

**Device Info(please complete the following information):**
 - OS: Linux (Debian 10)
 - Minecraft Version: 1.16.5
 - Version 1.4.0

**Additional context**
Works fine if you don't use shortcuts

**Comment by PotatoPresident** [comment]
Thats... weird. I can reproduce it though, should be able to fix. In the mean time, don't do that

**Comment by PotatoPresident** [comment]
Fixed in 1.4.1

**Comment by ethans0061** [comment]
Sweet! Thanks for the quick fix!
