### ISSUE TITLE
Dimension change when looking at an offline player's inventory

### ISSUE THREAD

**Issue by lolleap** [PotatoPresident/InvView#14]
**Description**
If a player has logged off in the end (possibly the nether as well, I haven't had time to test it) then an admin checks their inventory when the player logs back in they are in the same coordinates but in the overworld this can causes them to suffocate or die in lava especially if they have been in the end at an enderman farm for example.

**To Reproduce**
1. Player logs off in end (possibly nether as well, haven't had time to test)
2. Admin checks the offline player's inventory
3. Player logs back in
4. Player is now in the overworld at the same coordinates as they were in the end (nether)
5. Player is likely to die from fall damage/suffocation/lava etc.

**Expected behaviour**
Player should log back in in the same dimension as they logged off in.

**Device Info**
 - OS: Windows
 - Minecraft Version: 1.17 but this has happened in 1.16.5 as well
 - Mod version: 1.4.2

**Comment by yitzy299** [comment]
Do you have any other mods installed?

**Comment by PotatoPresident** [comment]
Reproduced. This is... concerning

**Comment by lolleap** [comment]
> Do you have any other mods installed?

Server side I have: Fabric API, Fabric-Discord link, Fat experience orbs, lithium and servux
