### ISSUE TITLE
Unable to view offline player's echests and inventories

### ISSUE THREAD

**Issue by crdtrd** [PotatoPresident/InvView#15]
**Describe the bug**
If I remember correctly you were able to view offline player's echests and inventories in 1.16. This does not seem to be the case in 1.17 from my tests. Entering the command results in no action, not even a message and nothing in the server logs.

**Expected behavior**
Be able to view offline player's echests and inventories.

**Screenshots**

**Device Info(please complete the following information):**
 - OS: Mac
 - 1.17
 - 1.4.2

**Additional context**
I am using /player from carpet mod to set up some starting items for players on the whitelist. I tested if altering the echest of a fake player would transfer to the real player, and it does. I tried viewing the inventory of my alt account that had actually been logged on and that didn't work either. The server is being locally hosted.

**Comment by pelophone** [comment]
this repro's for me too

**Comment by GamesaltGames** [comment]
Im having the same issue

**Comment by PotatoPresident** [comment]
It definitely works so it's most likely some sort of compat issue. Not much I can do without logs.

**Comment by CyroxTM** [comment]
this seems to cause a crash on hosted servers if this is attempted, seems to be a incompatibility with Player Roles mod?
the server was running Origins mod too
this is what gets printed out if attempted to access an offline players inventory:

`10.08 07:57:17 [Server] Server thread/INFO Error while reading data: player roles were not initialized
10.08 07:57:17 [Server] Server thread/ERROR Encountered an unexpected exception
10.08 07:57:17 [Server] INFO java.lang.NullPointerException: player roles were not initialized
10.08 07:57:17 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[custom.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.class_3222.getPlayerRoleSet(class_3222.java:1720) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at dev.gegy.roles.PlayerRoles$1.byEntity(PlayerRoles.java:58) ~[player-roles-1.4.2.jar:?]
10.08 07:57:17 [Server] INFO at dev.gegy.roles.api.RoleLookup.byPlayer(RoleLookup.java:25) ~[24fd5af1-2dd5-4946-989e-ad5598af7a37.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.class_3222.method_5476(class_3222.java:2199) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$24(EntityActions.java:310) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$3(EntityActions.java:69) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$8(EntityActions.java:113) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at io.github.apace100.apoli.util.Scheduler.lambda$new$0(Scheduler.java:49) ~[18478006-321c-438c-9736-0865a2c1b1ab.jar:?]
10.08 07:57:17 [Server] INFO at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[d9182cfe-7c8b-46a0-96c8-29746296c107.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.server.MinecraftServer.handler$zna000$onEndTick(MinecraftServer.java:3327) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:873) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.server.MinecraftServer.handler$bdm000$modifiedRunLoop(MinecraftServer.java:4890) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
10.08 07:57:17 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]`
