### ISSUE TITLE
Opening the Inventory Of An Online Player Doesn't Work

### ISSUE THREAD

**Issue by IAmSneak** [PotatoPresident/InvView#2]
Viewing their inventory results in it closing instantly.

**Comment by PotatoPresident** [comment]
Hmm, it works for me. I'll look into it
 Could you provide a server log?

**Comment by amnotbananaama** [comment]
I am also experiencing this bug. Nothing appears in the log, running the command succeeds for a second (I can see the actual items in their inventory), but it closes itself immediately.

**Comment by amnotbananaama** [comment]
Thank you for the quick fix! This is an excellent and highly useful mod

**Comment by PotatoPresident** [comment]
Np, it opens the player inventory like a chest but I didn't disable the distance check. Never noticed in dev because my test accounts were right next to each other. Took me awhile to figure it out.
