### ISSUE TITLE
Inventory Rollback

### ISSUE THREAD

**Issue by cmod31** [PotatoPresident/InvView#22]
**Is your feature request related to a problem? Please describe.**
I used the Plugin inventory rollback plus on paper servers but there is no fabric mod that allows this

**Describe the solution you'd like**
Because this fabric mod is viewing inventorys already would it be cool to backup inventorys at specific events like player leave or player death

**Describe alternatives you've considered**
If there is a mod that already does this let me know

**Comment by PotatoPresident** [comment]
[deathlog](https://modrinth.com/mod/deathlog) can do this
