### ISSUE TITLE
[1.18.2] No "protected" permission node

### ISSUE THREAD

**Issue by Merith-TK** [PotatoPresident/InvView#27]
Sorry for not using template, but there is no protected permission node to my knowledge

**Comment by PotatoPresident** [comment]
Well there is.

**Comment by Merith-TK** [comment]
![image](https://user-images.githubusercontent.com/10422110/187049966-80eaaa42-9210-4dae-9677-60316f21b712.png)
whats its node name?? as its not showing up in luckperms

**Comment by PotatoPresident** [comment]
`invview.protected`
