### ISSUE TITLE
Addition of View only permission

### ISSUE THREAD

**Issue by Jandfd99** [PotatoPresident/InvView#43]
Hello I would like to suggest the addition of a permission node that allows players to edit the inventory’s and enderchests, and without having this permission node players can only view the inventory’s and enderchests when opening them.

Or alternatively make a new command which is a view only command.

I need this in my server this I want my moderators the ability to view inventory’s and enderchests to look for illegal items, but I don’t want them to have the ability to edit these invens and echest (higher staff only will have perms to edit the inventory’s)

**Comment by PotatoPresident** [comment]
Already implemented with the `
invview.can_modify` permission node.

Similar to #32 and #39
