### ISSUE TITLE
Please update to support fabric 1.21.1 servers

### ISSUE THREAD

**Issue by BITS-US** [PotatoPresident/InvView#55]
I am running a fabric 1.21.1 server and would love to use this as I have used it in the past on other server that I have owned.

**Comment by Grqfes** [comment]
bump

**Comment by MISTERPUG51** [comment]
I'm running the latest version on my fabric 1.21.1 server with no problems.Not sure about 1.21.2 though because it just released yesterday.

**Comment by voruti** [comment]
> I'm running the latest version on my fabric 1.21.1 server with no problems.Not sure about 1.21.2 though because it just released yesterday.

Then it would be nice to mark this on Modrinth, as it currently isn't: https://modrinth.com/mod/invview/versions?l=fabric&g=1.21.1
