### ISSUE TITLE
Update Forge 1.16.4 ❤️

### ISSUE THREAD

**Issue by TsplayerT** [PotatoPresident/InvView#8]
**This mod is extremely useful, well done and somewhat simple (to be used).**

It would be interesting to have an update to be compatible with [Forge](http://files.minecraftforge.net/) (since most players prefer  ~~and me too~~)

**Comment by yitzy299** [comment]
:concern:

**Comment by PotatoPresident** [comment]
Sorry, fabric is much easier to develop for and I don't have much experience with forge.
