### ISSUE TITLE
Error occurs when trying to access offline player's inventory (probably mod conflict)

### ISSUE THREAD

**Issue by g5bb** [PotatoPresident/InvView#9]
**Describe the bug**
When trying to access an offline player's inventory/echest, it gives the error "An unexpected error occured trying to execute that command." Accessing online player's inventory/echest works perfectly fine.

**To Reproduce**
It only happens on my server, which has a lot of mods, I tested OpenInv alone on a server and it worked fine, so it must be mod conflict

**Expected behavior**
For me to be able to access the offline player's inventory/echest

**Screenshots**
Nothing really to screenshot, since it creates no error other than the one described above

**Device Info(please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.16.5
 - Version: v1.3.0

**Additional context**
Mods:
Blocklogger
Carpet Extra
Damage Tilt
Dispenser Portal Fix
Fabric API
Carpet
MumbleLink
FastFurnace
Hydrogen
Image2Map
ItemFlexer
Krypton
LazyDFU
Lithium
LuckPerms
More Blocks Mod
Netherite Plus
Random Patches
Server Tick
Servux
Sit
Spark
Starlight
Wither Cage Fix

**Comment by PotatoPresident** [comment]
Hmm. I downloaded everything and couldn't reproduce this. Is there anything in the console?

Also dispenser portal fix is unnecessary in 1.16.5

**Comment by yitzy299** [comment]
Install https://github.com/ByMartrixx/wdmcf and then send the stacktrace in the server console please

**Comment by g5bb** [comment]
> Hmm. I downloaded everything and couldn't reproduce this. Is there anything in the console?
> 
> Also dispenser portal fix is unnecessary in 1.16.5

Nope nothing happens in console

**Comment by g5bb** [comment]
> Install https://github.com/ByMartrixx/wdmcf and then send the stacktrace in the server console please

Okay

**Comment by g5bb** [comment]
This is the error it gives in console now: [](https://pastebin.com/raw/vVFK6j4V)

**Comment by PotatoPresident** [comment]
Figured it out. It seems luck perms is trying to check if the offlineplayers inventory is protected but can't. Working on a fix
